### PR TITLE
First implementation for subdomains to serve country selection

### PR DESCRIPTION
**Pull request by gousta**

### CODE REVIEW

**Comment by niksumeiko** [comment]
@gousta, I'm experiencing a problem within many controllers now, since all of them expects first parameter a string – which is `{country}` defined in a very parent routes group.



Shall I manually list this parameter as first in every controller? Or you have a better solution to exclude it from all of them at once? Country is accessible via `config('app.country')` anyway.

**Comment by niksumeiko** [comment]
Hey @gousta, what do you think of a controllers problem arisen after adding `{country}` parameter to every route (wrapping everything into country routes group)? See my previous comment with details.

**Comment by gousta** [comment]
@niksumeiko I already wrapped them using domain group. Maybe the controller methods have first parameter. I'll check it now

**Comment by gousta** [comment]
@niksumeiko also, I've added some new ENV vars, maybe that affects it as well. 
It seems to work for me.

screen shot 2017-05-15 at 19 08 17

**Comment by niksumeiko** [comment]
@gousta, will give it a try once again. Wondering why all controllers on my local now expects first argument to be country string… And for you it works as is.

**Comment by niksumeiko** [comment]
Only when I explicitly enforce route to forget `{country}` parameter within the middleware before it reaches the controller, everything works — see de4b635. 

Otherwise, [exception](#issuecomment-300000263) is thrown on almost very controller.

**Comment by gousta** [comment]
We should delete the branch now that this is merged

**Comment by gousta** [comment]
@niksumeiko added another commit which handles not found country by redirecting to www

**Comment by gousta** [comment]
> Now I have to figure out how to run multi-subdomain staging app on our testing server.
I can help with that

**Comment by gousta** [comment]
Please merge the changes into sala so I can start working on the language part.

**Comment by niksumeiko** [comment]
@gousta, where's that commit you're referring to? Have you added it to this PR branch `feature/country-subdomain`?

**Comment by niksumeiko** [comment]
Found it abc7710, merging it to `sala` now.

**Comment by niksumeiko** [comment]
@gousta, your latest commit is merged to `sala`. I'm closing this branch now. Please continue checking out new one from `sala` 👌🏻

**Pull request merged**
